server:
  port: 8301

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: dev123
    hikari:
      maximum-pool-size: 100   # 太小容易被打满
      connection-timeout: 30000

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl      #MyBatis的sql日志，输出到控制台
    map-underscore-to-camel-case: true  #开启MyBatis的驼峰命名自动映射开关 a_colum --->  aColum